estack:
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CI=True -DCONFIG_POLL_TMO=100
    - make
    - make run_netdev
    - make run_ip
    - make run_ipfrag
    - make run_ipforward
    - make run_events
    - make run_udptest
  only:
    - master