estack:
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CI=True
    - make
    - make run_netdev
    - make run_ip
    - make run_ipfrag
    - make run_ipforward
  only:
    - master