SET(ESTACK_PORT_DIR ports/unix)
SET(ESTACK_PORT_SRCS
${ESTACK_PORT_DIR}/unix.c)
SET(ESTACK_PORT_HEADERS
${ESTACK_PORT_DIR}/arch.h)
SET(ESTACK_PORT_INCLUDE_DIR ${PROJECT_SOURCE_DIR}/source/ports/unix)

find_package(Threads REQUIRED)
SET(ESTACK_SYSTEM_LIBS ${CMAKE_THREAD_LIBS_INIT})