SET(ESTACK_PORT_DIR ports/win32)
SET(ESTACK_PORT_SRCS
${ESTACK_PORT_DIR}/win32.c)
SET(ESTACK_PORT_HEADERS
${ESTACK_PORT_DIR}/arch.h)
SET(ESTACK_PORT_INCLUDE_DIR ${PROJECT_SOURCE_DIR}/source/ports/win32)

find_package(Threads REQUIRED)
SET(ESTACK_SYSTEM_LIBS ${CMAKE_THREAD_LIBS_INIT})